### PR TITLE
Update

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by magneticflux-** [comment]
Could you explain the phrase "переведено сообществом модовестник" before I merge this?

**Comment by ghost** [comment]
This is basically an explanation, how correct chop tree

**Comment by magneticflux-** [comment]
@vanja-san I'd like your opinion on this translation before I accept it since you translated it originally.

**Comment by ghost** [comment]
Wait ... You'll be waiting a long time

**Comment by YuRaNnNzZZ** [comment]
> 
> 
> Could you explain the phrase "переведено сообществом модовестник" before I merge this?

advertisement of his VK community

**Comment by magneticflux-** [comment]
That's what I feared. I'd be happy to include credit in the list of contributors, but I won't allow unsolicited advertisement.

**Comment by FinnT730** [comment]
I know that I am late, but they have been doing this a lot, it seems.....

**Pull request closed without merging**
